config/routes.rb
# TODO autoloading order changed. This should be managed by configs instead:
# https://guides.rubyonrails.org/v7.0/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots
require_relative '../app/controllers/api/v1/base'
require_relative '../app/controllers/api/base'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    resources :restrooms, except: [:edit, :destroy]

    namespace :api do
      resources :docs, only: [:index]
    end

    mount API::Base => '/api'

    get '/contact', to: 'contacts#new'
    get "/*id" => 'pages#show', as: :page, format: false
    root 'pages#index'

    resources "contacts", only: [:new, :create]
end

app/views/layouts/_disqus_tag.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
  <% if Rails.env != 'production' %>
    var disqus_developer = 1;
  <% end %>

  var disqus_shortname = 'refugerestrooms';
  <% if defined? identifier %>
    var disqus_identifier = '<%= identifier %>';
  <% end %>
  <% if defined? title %>
    var disqus_title = '<%= title %>';
  <% end %>
  <% if defined? url %>
    var disqus_url = '<%= url %>';
  <% end %>

  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/layouts/_filters.html.haml
/ Filters for ada, unisex and map toggle
.row
  .col-xs-12.headroom
    #filters.clearfix
      .btn-group{:data => {:toggle => "buttons"}}
        - if params[:ada].present? && params[:ada] == 'true'
          %label#ada_filter.filter.text.btn.whitebutton.active
            %input{:type => "checkbox"}
            %i.fa.fa-wheelchair
        - else
          %label#ada_filter.filter.text.btn.whitebutton
            %input{:type => "checkbox"}
            %i.fa.fa-wheelchair
        - if params[:unisex].present? && params[:unisex] == 'true'
          %label#unisex_filter.filter.text.btn.whitebutton.active
            %input{:type => "checkbox"}
            %i.fa.fa-transgender-alt
        - else
          %label#unisex_filter.filter.text.btn.whitebutton
            %input{:type => "checkbox"}
            %i.fa.fa-transgender-alt
      .btn-group.mapToggle{:data => {:toggle => "buttons"}}
        %label#map_filter.filter.btn.whitebutton
          %input{:type => "checkbox"}
          Map
        %label#list_filter.filter.btn.whitebutton.active
          List

app/views/layouts/_footer.html.haml
%footer
  .footer
    %a.iconLink{:href => "https://github.com/RefugeRestrooms/refugerestrooms", :aria => { :label => t('.aria-labels.github')}}
      %i.icon.fa.fa-github-square.fa-3x
    %a.iconLink{:href => "https://twitter.com/refugerestrooms", :aria => { :label => t('.aria-labels.twitter')}}
      %i.icon.fa.fa-twitter-square.fa-3x
    %a.iconLink{:href => "https://www.facebook.com/refugerestrooms", :aria => { :label => t('.aria-labels.facebook')}}
      %i.icon.fa.fa-facebook-square.fa-3x
    %a.iconLink{:href => contact_path, :aria => { :label => t('.aria-labels.email')}}
      %i.icon.fa.fa-envelope.fa-3x
    %br/
    = t('.refuge-restrooms-is-open-source')
    %a{:href => "https://github.com/RefugeRestrooms/refugerestrooms"} #{t('.code-on-github')}
    %br/
    = t('.contribute-to-the-project')
    %a{:href => "https://patreon.com/refugerestrooms"} #{t('.on-patreon')}
    %br/
    = "\&copy; #{t('.copyleft')}  #{Date.today.year} #{t('.refuge-restrooms')}".html_safe
    %br/
    %br/
    = link_to 'English', request.query_parameters.merge(locale: 'en'), class: 'locale_link'
    &bull;
    = link_to 'Español', request.query_parameters.merge(locale: 'es'), class: 'locale_link'
    &bull;
    = link_to 'Filipino/Tagalog', request.query_parameters.merge(locale: 'fil'), class: 'locale_link'
    &bull;
    = link_to 'Français', request.query_parameters.merge(locale: 'fr'), class: 'locale_link'
    &bull;
    = link_to 'हिन्दी', request.query_parameters.merge(locale: 'hi'), class: 'locale_link'
    &bull;
    = link_to 'Italiano', request.query_parameters.merge(locale: 'it'), class: 'locale_link'
    &bull;
    = link_to 'polski', request.query_parameters.merge(locale: 'pl'), class: 'locale_link'
    &bull;
    = link_to 'Português do Brasil', request.query_parameters.merge(locale: 'pt-BR'), class: 'locale_link'

app/views/layouts/_head.html.haml
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
%title= content_for?(:title) ? yield(:title) : "REFUGE Restrooms"
%meta{:content => content_for?(:description) ? yield(:description) : "Refuge Restrooms", :name => "description"}/
%meta{:content => "gender neutral restrooms,gender,neutral,restrooms, unisex restrooms, unisex, restrooms, refuge restrooms, refuge, restrooms", :name => "keywords"}/
%link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet", :name => "fontawesome"}/
%meta{:content => "RefugeRestrooms.org", :name => "author"}/
%meta{:content => "initial-scale=1, maximum-scale=1", :name => "viewport"}/

%script{:src => "https://maps.googleapis.com/maps/api/js?v=quarterly&libraries=places&key=AIzaSyCEjTsxAkHtqGhECdsqNwwpW5pslQcJuuE"}
= javascript_include_tag "https://www.google.com/recaptcha/api.js", :async => true, :defer => true
= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
= javascript_pack_tag "application", "data-turbolinks-track": "reload"
= csrf_meta_tags
= render 'layouts/piwik_tag'

app/views/layouts/_header.erb
<% # ADA filter and UNISEX filter have inconsistant default boolean values because i'm using the format originally used by the Safe2Pee db because the engineers were stupid and used different 1 for ADA and 0 for UNISEX. %>


<div class="header">

  <div class="search">
  	<div class="toiletLogo" id="logo"></div>
  	<%= form_tag bathrooms_path, :method => :get do %>
  	<div class="searchBarContainer">
  		<%= text_field_tag :search, params[:search], :class => "searchBar" %>
  	</div>
  	<%= submit_tag "Search", :type => 'button', :name => nil, :class=> "linkbutton searchButton submitButton" %>
  	<%= submit_tag "", :type => 'button', :name => nil, :class=> "linkbutton currentLocationButton" %>
  	<%= hidden_field_tag :lat, "" %>
  	<%= hidden_field_tag :long, "" %>
  </div>


  <div class="nav">
    <div class="adaFilter filter">
      <%= check_box_tag :adafilter, 1, params[:adafilter] == '1', :class => 'adacheck submitButton' %>
      <label for="adafilter" class="adaFilterlabel linkbutton <%= params[:adafilter] == '1' ? "" : "buttonOn" %>"><span class="hiddenText">ADA Compliant Filter</span></label>
    </div>

    <div class="unisexFilter filter">
      <%= check_box_tag :unisexfilter, 0, params[:unisexfilter] == '0', :class => 'unisexcheck submitButton' %>
      <label for="unisexfilter" class="unisexFilterlabel linkbutton <%= params[:unisexfilter] == '0' ? "buttonOn" : "" %>"><span class="hiddenText">Unisex Filter</span></label>
    </div>

    <div class="mapToggle">
      <div class="mapTogglelabel linkbutton">
        Map View
      </div>
    </div>
  </div>

  <% end %>

</div>

app/views/layouts/_header.html.haml
.header
  .container
    = render 'layouts/navigation'
    = render 'layouts/search'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == "notice" ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.container
  .row.min-headroom
    .col-xs-12.nav-column
      %nav.nav.navbar-default{:role => "navigation"}
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          = link_to root_path, id: 'logo', class: 'toiletLogo' do
            .navbar-brand Refuge Restrooms
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only= t('.toggle-navigation-button-label')
            %i.fa.fa-bars.fa-2x
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to t('.submit-a-new-restroom-hyperlink-label'), new_restroom_path
            %li= link_to t('.about-hyperlink-label'), page_path('about')
            %li= link_to t('.contact-hyperlink-label'), contact_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = t('.resources-dropdown-button-label')
                %b.caret
              %ul.dropdown-menu
                %li= link_to t('.download-unisex-restroom-signs-hyperlink-label'), page_path('signs')
                %li= link_to t('.public-api-hyperlink-label'), api_docs_path
        / /.navbar-collapse

app/views/layouts/_piwik_tag.html.haml
<!-- Matomo -->
:javascript
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://refugerestrooms.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
<!-- End Matomo Code -->

app/views/layouts/_search.html.haml
- splash = false if local_assigns[:splash].nil?

.row.search-container
  = form_tag restrooms_path, class: "search-restrooms-form", method: :get do
    = hidden_field_tag :lat, ""
    = hidden_field_tag :long, ""
    = hidden_field_tag :locale, current_locale
    .input-group
      = text_field_tag :search, params[:search], class: "form-control search-bar", aria: {label: t("search_bar.enter_location")}
      .input-group-btn
        %button.btn.btn-light-purple.submit-search-button{type: "button", title: t('.search'), value: t('.search'), aria: { label: t('.search') }}
          %i.fa.fa-search.fa-2x
          %i.fa.fa-refresh.fa-spin.fa-2x
        %button.btn.btn-light-purple.current-location-button{type: "button", title: t('.search-by-current-location'), aria: { label: t('.search-by-current-location') }, value: (splash ? t('.search-by-current-location') : nil ) }
          %i.fa.fa-location-arrow.fa-2x
          %i.fa.fa-refresh.fa-spin.fa-2x

app/views/layouts/_search_js.html.erb
<script type="text/javascript">
  var searchDefaultText = "1 Embarcadero Center, San Francisco, CA";
  //Try using google maps search autocomplete
  var input = (document.getElementById('search'));
  var searchBox = new google.maps.places.SearchBox((input));

  var search = $("#search");

  $(function(){
    $("#logo").click(function(){
      window.location = "http://" + window.location.host;
    });

    setDefaultText(search, searchDefaultText);

    $(".submitButton").click(function(){
      $(".search").find("form").submit();
    });


    $(".search").find("form").submit(function(event){
      //remove default text on empty search
      preventSearchWithDefault(search);

      if($("#lat").val() == ""
          || $("#long").val() == ""
          || $("#lat").val() == undefined
          || $("#long").val() == undefined
      ){
        event.preventDefault();
        searchLocation(search.val());
      }
    });

    $(".currentLocationButton").click(function(){
        searchCurrent();
    });
  });

  function setDefaultText(element, text){
    //ensure we're not overwriting a value
    if(element.val() == ""){
      element.val(text);
      element.addClass("fadedText");

      //remove effects on focus
      element.focus(function(){
        element.removeClass("fadedText");
        element.val("");

        //when unfocused set back to default if there is no text
        element.blur(function(){setDefaultText(element,text);});
      });
    }
  }

  function preventSearchWithDefault(searchBox){
    //use class to determine if the text has been modified or not
    if(searchBox.hasClass("fadedText") && searchBox.val() == searchDefaultText){
      //set search field back to blank
      searchBox.val("");
    }
  }
</script>

app/views/layouts/application.html.haml
!!!
%html{lang: I18n.locale}
  %head
    = render 'layouts/head'
  %body
    - if @mobile
      - # For iOS and Android clients redirecting to our pages for input of bathrooms, we will hide the header.
      %header
        = render 'layouts/header'
    %main
      .container
        = render 'layouts/messages'
        = yield
        = render 'layouts/footer'

app/views/layouts/splash.html.haml
!!!
%html{lang: I18n.locale}
  %head
    = render 'layouts/head'
  %body
    .splash-background
      = render 'layouts/navigation'
      .container
        = yield